title: "Blog personal"
description: "Estudios, gráficos y Proyectos de Inversión Pública - Perú"
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
theme: jekyll-theme-leap-day
