title: "Blog personal"
description: "Academia de Proyectos de Inversión Pública"
show_downloads: true
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
theme: jekyll-theme-dinky
sass:
  style: compressed
