title: "Academia de Inversión Pública"
description: "amaru_fo"
show_downloads: true
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
theme: jekyll-theme-dinky
sass:
  style: compressed
